Repository mash-up-kr/mashup-ios, pull requests merged in 2022-07, with the labels that each got.

#27 알림창 구현
  MashUp-iOS/MashUp-UIKit/MUActionAlertViewController/MUActionAlertViewController.swift
  MashUp-iOS/MashUp-UIKit/MUActionAlertViewController/MUAlertAction.swift
  MashUp-iOS/MashUp-UIKit/MUActionAlertViewController/MUAlertView.swift
  MashUp-iOS/MashUp-UIPreview/Source/PreviewMenu.swift
  MashUp-iOS/MashUp-UIPreview/Source/PreviewMenuViewController.swift
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
Labels: feature

#29 MyPageRuleViewController 구현
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/DotLabel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MyPageRuleViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/RuleHeaderView.swift
Labels: feature

#33 Feature/membership withdrawal
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/Domain/MyPage/MembershipWithdrawalService.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MembershipWithdrawalReactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MembershipWithdrawalViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/DontForgetMashUpView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/DotLabel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/RuleHeaderView.swift
  MashUp-iOS/MashUp-iOSTests/Specs/MembershipWithdrawalReactorSpec.swift
Labels: feature

#31 Feauter/event list UI
  MashUp-iOS/MashUp-Core/UIKit+/NSCollectionLayoutSectionFactory.swift
  MashUp-iOS/MashUp-Core/UIKit+/UICollectionView+.swift
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/Domain/Seminar/Seminar.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Root/RootController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/Seminar Detail/SeminarDetailCellModel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/Seminar Detail/SeminarDetailFormatter.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/Seminar Detail/SeminarDetailSection.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/Seminar Detail/SeminarDetailViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/Seminar Detail/View/SeminarDetailCell.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/Seminar Detail/View/SeminarDetailFooterView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/Seminar Detail/View/SeminarDetailHeaderView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/SeminarScheduleSection.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/SeminarScheduleViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/SeminarSchedulerFormatter.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/View/AttendenceTimeAndCheckView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/View/NowAttendenceView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/View/SeminarCardCell.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Seminar Schedule/View/SeminarHeaderView.swift
Labels: feature

#32 [Feature] 마이페이지 UI 작업, 더미데이터 연동 작업 완료
  MashUp-iOS/MashUp-Auth/Fake(deprecated)/FakeUserAuthService.swift
  MashUp-iOS/MashUp-Core/Foundation+/Collection+.swift
  MashUp-iOS/MashUp-Core/UIKit+/UITableView+.swift
  MashUp-iOS/MashUp-UIKit/Image.xcassets/img_profile_team.imageset/Contents.json
  MashUp-iOS/MashUp-UIKit/Image.xcassets/img_profile_team.imageset/img_profile_team.pdf
  MashUp-iOS/MashUp-UIKit/Image.xcassets/mascot_body.imageset/Contents.json
  MashUp-iOS/MashUp-UIKit/Image.xcassets/mascot_body.imageset/mascot.pdf
  MashUp-iOS/MashUp-UIKit/Image.xcassets/mascot_hands.imageset/Contents.json
  MashUp-iOS/MashUp-UIKit/Image.xcassets/mascot_hands.imageset/moscot_hands.pdf
  MashUp-iOS/MashUp-UIKit/Image.xcassets/mypage_card.imageset/Contents.json
  MashUp-iOS/MashUp-UIKit/Image.xcassets/mypage_card.imageset/mypage_card.pdf
  MashUp-iOS/MashUp-UIKit/Image.xcassets/placeholder.imageset/Contents.json
  MashUp-iOS/MashUp-UIKit/Image.xcassets/placeholder.imageset/placeholder.pdf
  MashUp-iOS/MashUp-UIKit/UIImage+.swift
  MashUp-iOS/MashUp-User/Generation.swift
  MashUp-iOS/MashUp-User/UserSession.swift
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MashUp-iOS/MashUp-iOS/Source/Domain/ClubActivityHistory/ClubActivityHistory.swift
  MashUp-iOS/MashUp-iOS/Source/Domain/ClubActivityHistory/ClubActivityRepository.swift
  MashUp-iOS/MashUp-iOS/Source/Domain/ClubActivityHistory/ClubActivityScore.swift
  MashUp-iOS/MashUp-iOS/Source/Domain/ClubActivityHistory/ClubActivityService.swift
  MashUp-iOS/MashUp-iOS/Source/Domain/ClubActivityHistory/FakeClubActivityRepository.swift
  MashUp-iOS/MashUp-iOS/Source/Domain/Debug/DebugSystem.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Home/HomeTabBarController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/ClubActivityScoreRule/ClubActivityScoreRuleViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/ClubActivityScoreRule/DotLabel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/ClubActivityScoreRule/RuleHeaderView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MyPageFormatter.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MyPageReactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MyPageSection.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MyPageViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/ClubActivityHistoryCell.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/ClubActivityHistorySectionHeaderView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/ClubActivityHistoryTitleHeaderView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/EmptyClubActivityHistoryView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/MyPageHeaderView+Rx.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/MyPageHeaderView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/MyPageSummaryBar+Rx.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/View/MyPageSummaryBar.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Root/RootController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Step1/SignUpStep1ViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Terms Agreement Popup/View/TermsAgreementView+Rx.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Withdrawal/MembershipWithdrawalReactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Withdrawal/MembershipWithdrawalViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Withdrawal/View/DontForgetMashUpView.swift
  MashUp-iOS/MashUp-iOSTests/Specs/HomeReactorSpec.swift
  MashUp-iOS/MashUp-iOSTests/Specs/MyPageReactorSpec.swift
  MashUp-iOS/MashUp-iOSTests/TestDoubles/ClubActivityHistoryCellModel+Stub.swift
  MashUp-iOS/MashUp-iOSTests/TestDoubles/MyPageHeaderViewModel+Stub.swift
  MashUp-iOS/MashUp-iOSTests/TestDoubles/MyPageSummaryBarModel+Stub.swift
  MashUp-iOS/MashUp-iOSTests/TestDoubles/UserSession+Stub.swift
Labels: feature, 🐳 남수PR완료

#35 ✨SettingView 레이아웃 구현 완료
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/Screen/ClubActivityScoreRule/ClubActivityScoreRuleViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/ClubActivityScoreRule/DotLabel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/ClubActivityScoreRule/RuleHeaderView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/ClubActivityScoreRule/View/DotLabel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/ClubActivityScoreRule/View/RuleHeaderView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/MyPageViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Setting/SettingViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Setting/View/SNSButton.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Setting/View/SettingMenuButton.swift
Labels: feature, 🐳 남수PR완료

#34 [Feature] 네트워크 레이어 공통에러 처리 / 공통 에러 타입 구현
  MashUp-iOS/MashUp-Core/MashUpError.swift
  MashUp-iOS/MashUp-Network/Error/InternalError.swift
  MashUp-iOS/MashUp-Network/Error/NetworkError.swift
  MashUp-iOS/MashUp-Network/Model/ResponseModel.swift
  MashUp-iOS/MashUp-Network/Network/HTTPClient.swift
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/ClubActivityScoreRule/ClubActivityScoreRuleViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/ClubActivityScoreRule/DotLabel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/My Page/ClubActivityScoreRule/RuleHeaderView.swift
Labels: feature, 🐳 남수PR완료

#36 [Feature] 회원가입 플로우 수리 / 디테일 적용
  MashUp-iOS/MashUp-Auth/Fake(deprecated)/FakeUserAuthService.swift
  MashUp-iOS/MashUp-Auth/Repository/SignUpAPI.swift
  MashUp-iOS/MashUp-Auth/Repository/SignUpResponse.swift
  MashUp-iOS/MashUp-Auth/Repository/UserSessionRepository.swift
  MashUp-iOS/MashUp-Auth/Service/UserAuthService.swift
  MashUp-iOS/MashUp-Auth/Service/UserAuthServiceImp.swift
  MashUp-iOS/MashUp-Auth/SignUpError.swift
  MashUp-iOS/MashUp-Auth/UserAuthService.swift
  MashUp-iOS/MashUp-Auth/UserAuthServiceProvider.swift
  MashUp-iOS/MashUp-Core/UIKit+/EventThroughView.swift
  MashUp-iOS/MashUp-Core/UIKit+/UIImageView+.swift
  MashUp-iOS/MashUp-Core/UIKit+/UIViewController+.swift
  MashUp-iOS/MashUp-Network/API/MashUpAPI.swift
  MashUp-iOS/MashUp-Network/Network/NetworkConfig.swift
  MashUp-iOS/MashUp-PlatformTeam/PlatformTeam.swift
  MashUp-iOS/MashUp-SignUpCode/Domain/Fake/FakeSignUpCodeVerificationService.swift
  MashUp-iOS/MashUp-SignUpCode/Presentation/SignUpCodeReactor.swift
  MashUp-iOS/MashUp-SignUpCode/Presentation/SignUpCodeViewController.swift
  MashUp-iOS/MashUp-UIKit/MUActionAlertViewController/MUActionAlertViewController.swift
  MashUp-iOS/MashUp-UIKit/MUActionAlertViewController/MUAlertAction.swift
  MashUp-iOS/MashUp-UIKit/MUActionAlertViewController/MUAlertView.swift
  MashUp-iOS/MashUp-UIKit/MUButton/MUButtonStyle.swift
  MashUp-iOS/MashUp-UIKit/MUTextField/MUTextField.swift
  MashUp-iOS/MashUp-UIKit/UIImage+.swift
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/App/AppDelegate.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Root/RootController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign In/SignInReactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign In/SignInStep.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign In/SignInViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Personal Infomation Policy/PersonalInfomationPolicyReactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Personal Infomation Policy/PersonalInfomationPolicyWebViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Step1/SignUpStep1Reactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Step1/SignUpStep1ViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Step2/SignUpStep2Reactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Step2/SignUpStep2ViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Terms Agreement Popup/TermsAgreementPopupViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Terms Agreement Popup/TermsAgreementReactor.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Terms Agreement Popup/View/TermsAgreementView.swift
Labels: feature, ☠️ do not merge, 🐳 남수PR완료

#41 [Fix] 네트워크 재요청 버그 수정
  MashUp-iOS/MashUp-Auth/Service/UserAuthService.swift
  MashUp-iOS/MashUp-Core/Concurrency/AsyncSequence+.swift
  MashUp-iOS/MashUp-Network/API/MashUpAPI.swift
  MashUp-iOS/MashUp-Network/Network/HTTPClient.swift
  MashUp-iOS/MashUp-SignUpCode/Domain/SignUpCodeVerificationService.swift
  MashUp-iOS/MashUp-SignUpCode/Presentation/SignUpCodeReactor.swift
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/App/AppDelegate.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/Sign Up/Step2/SignUpStep2ViewController.swift
Labels: 🐛 bug fix

#37 출석현황 디자인 수정사항 적용 및 컬러적용
  MashUp-iOS/MashUp-PlatformTeam/PlatformRepository.swift
  MashUp-iOS/MashUp-iOS.xcodeproj/project.pbxproj
  MashUp-iOS/MashUp-iOS/Source/Domain/Attendance/AttendanceMember.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceDetail/Extension/AttendanceStatus+Presentation.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceDetail/PlatformAttendanceDetailViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceDetail/View/AttendanceDetailCell.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceDetail/View/AttendanceStatusCircleView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceDetail/View/AttendanceStatusCircleViewModel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceStatus/PlatformStatusViewController.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceStatus/View/AttendanceStatusRectangleView.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceStatus/View/AttendanceStatusRectangleViewModel.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceStatus/View/PlatformAttendanceCell.swift
  MashUp-iOS/MashUp-iOS/Source/Screen/PlatformAttendanceStatus/View/PlatformAttendanceHeaderView.swift
Labels: feature
